Algoritmo "Area do Pentágono"
// Disciplina  : [Logica de programação com Visualg]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Automatização para descobrir a área de um Pentágono
// Autor(a)    : Marcos Vinicius
// Data atual  : 23/03/2026
Var
// Seção de Declarações das variáveis
lado:real
altura:real
resultado:real



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("digite o valor da altura do pentagono")
leia(lado)
escreva("digite o valor da altura do pentagono")
leia(altura)
resultado<- (lado * altura * 5)
escreva("o resultado da area do pentagono é:",resultado)

        

Fimalgoritmo