Algoritmo "Enquanto"

// Disciplina  :[Lógica de Programação com VisualG]

// Professor   :Jailson Costa dos Santos

// Descrição   : Exemplo de laço de repetição

// Autor(a)    : Marcos

// Data atual  : 13/04/2026

Var

   // Seção de Declarações das variáveis

   contadora:inteiro

Inicio

   // Seção de Comandos, procedimento, funções, operadores, etc...

   enquanto contadora<15 faça

      Escreval("marc")

      contadora<-contadora+1

   fimenquanto

Fimalgoritmo
