Algoritmo "L01A"
// Disciplina   : Lógica de Programação com o VISUALG
// Professor   : Jailson Costa Dos Santos 
// Descrição   :  ler uma temperatura em graus celsius e convertela em graus Fanhenheit.
// Autor(a)    : Marcos Vinicius
// Data atual  : 04/04/2026
Var
// Seção de Declarações das variáveis
GrausCelsius:real
GrausFahrenheit:real
Formula:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite o valor da temperatura em graus Celsius")
leia(GrausCelsius)
formula<- ( 9 * GrausCelsius + 160) /5
escreval("a formula de conversao de celsius para fahreheit é: ",formula)


Fimalgoritmo