Algoritmo "L03A"
// Disciplina   : Lógica de Programação com o VISUALG
// Professor   : Jailson Costa Dos Santos 
// Descrição   : Calcular e apresentar o valor do volume de uma lata
// Autor(a)    : Marcos Vinicius
// Data atual  : 04/04/2026
Var
// Seção de Declarações das variáveis
volume:real
altura:real
raio:real



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("digite o valor da altura da lata de oleo")
leia(altura)
escreval("digite o valor do raio da lata")
leia(raio)
volume<-( )





Fimalgoritmo