Algoritmo "L08A"
// Disciplina   : Lógica de Programação com o VISUALG
// Professor   : Jailson Costa Dos Santos 
// Descrição   : calcular e apresentar o volume de uma caixa retangular
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2026
Var
// Seção de Declarações das variáveis
volume:real
comprimento:real
largura:real
altura:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("digite o valor do comprimento")
leia(comprimento)
escreval("digite o numero da largura")
leia(largura)
escreval("digite a altura")
leia(altura)
volume<-(comprimento * largura * altura)
escreval("o volume de uma caixa retangular é: ",volume)


Fimalgoritmo