Algoritmo "L09A"
// Disciplina   : Lógica de Programação com o VISUALG
// Professor   : Jailson Costa Dos Santos 
// Descrição   : resultado do quadrado da diferença
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2026
Var
// Seção de Declarações das variáveis
numero1:inteiro
numero2:inteiro
resultado:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("digite o valor do primeiro inteiro")
leia(numero1)
escreval("digite o numero do segundo inteiro")
leia(numero2)
resultado<- (numero1 - numero2) * (numero1 - numero2)
escreval("o quadrado da diferença é ",resultado)




Fimalgoritmo