Algoritmo "L10A"
// Disciplina   : Lógica de Programação com o VISUALG
// Professor   : Jailson Costa Dos Santos 
// Descrição   : real em dolar
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2026
Var
// Seção de Declarações das variáveis
reais:real
dolar:real
cotacao:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("digite quanto temos em cotaçao")
leia(cotacao)
escreval("digite a quantidade de dolares")
leia(dolar)
reais<- (dolar * cotacao)
escreval("o valor em reais é: ",reais)






Fimalgoritmo