Algoritmo "L11A"
// Disciplina   : Lógica de Programação com o VISUALG
// Professor   : Jailson Costa Dos Santos 
// Descrição   : soma dos tres quadrados
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2026
Var
// Seção de Declarações das variáveis
quadrado1:real
quadrado2:real
quadrado3:real
resultado:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("digite o valor do pprimeiro quadrado")
leia(quadrado1)
escreval("")
escreval("digite o valor do quadrado dois")
leia(quadrado2)
escreval("digite o valor do terceiro quadrado")
leia(quadrado3)
resultado<- (quadrado1 ^ 2)  + (quadrado2 ^ 2) + (quadrado3 ^ 2)
escreval("a soma dos tres quadrado ao quadrado é: ",resultado)









Fimalgoritmo