Algoritmo "L13A"
// Disciplina   : Lógica de Programação com o VISUALG
// Professor   : Jailson Costa Dos Santos 
// Descrição   : efetuar a leitura de quatro valores inteiros e ao final apresentar o resultado
// Autor(a)    : Marcos Vinicius
// Data atual  : 06/04/2026
Var
// Seção de Declarações das variáveis
numero1:inteiro
numero2:inteiro
numero3:inteiro
numero4:inteiro
produto:inteiro
soma:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite o priemiro valor")
leia(numero1)
escreval("digite o segundo valor")
leia(numero2)
escreval("digite o terceiro valor")
leia(numero3)
escreval("digite o quarto valor")
leia(numero4)
produto<- (numero1 * numero3)
escreval("o resultado do primeiro com o terceiro é: ",produto)
soma<- (numero2 + numero4)
escreval("o resultado da soma do segundo com o quarto é: ",soma)


Fimalgoritmo