Algoritmo "Leia a base e a altura de um paralelogramo e calcule sua área. "
// Disciplina   : Lógica de Programação com o VISUALG
// Professor   : Jailson Costa Dos Santos 
// Descrição   : ler a base e altra de um paralelogramo e calcula-lo
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis
//entradas//
base:real
altura:real
resultado:real

 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("digite o valor da base do paralelogramo") //saida
leia(base)   //entrada
escreval("digite o valor da altura do paralelogramo") //saida
leia(altura)  //entrada
resultado<- (base*altura) //processamento
escreval("o resultado da area do paralelogramo é: ", resultado) //saida







Fimalgoritmo