Algoritmo "parimpar"
// Disciplina   : Lógica de Programação com o VISUALG
// Professor   : Jailson Costa Dos Santos
// Descrição   : numeros par e impar
// Autor(a)    : Marcos Vinicius
// Data atual  : 01/04/2026
Var
   // Seção de Declarações das variáveis
   numero1:real



Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("digite um numero ")
   leia(numero1)
   se numero1 mod 2 = 0 entao
      escreval("o numero é par ",)
   senao
      escreval("o numero é impar ")
   fimse



Fimalgoritmo

2 5 10 20 50 100 200