Algoritmo "perímetro de um retangulo"
// Disciplina   : Lógica de Programação com o VISUALG
// Professor   : Jailson Costa Dos Santos 
// Descrição   : ele solicita a base e a altura e exibe o perímetro
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis
//entradas//
altura:real
base:real
resultado:real
 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("digite o valor da base do retangulo ") //saida//
leia(base)   //entrada//
escreval("") //saida
escreva("digite o valor da altura ") //saida//
leia(altura) //entrada//
escreval("") //saida//
resultado<- 2*(base+altura) //processamento//
escreva("o valor do perimetro é: ", resultado) //saida/


Fimalgoritmo