Algoritmo "Quanto você ganha por hora"
// Disciplina  : [Logica de programação com Visualg]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Automatização para descobrir a área de um Losango
// Autor(a)    : Marcos Vinicius
// Data atual  : 23/03/2026
Var
// Seção de Declarações das variáveis
eleitores:real
votos:real
branco:real
nulo:real
valido:real
resultado:real




   Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
escreva("quantos eleitores estao no municipio?")
leia(eleitores)
escreva("quantos votos em banco tiveram? ")
leia(branco)
escreva("quantos votos tiveram em nulo? ")
leia(nulo)
escreva("quantos votos validos tiveram? ")
leia(valido)
resultado<- (eleitores / branco *
escreva("o percentuais de votos são: ",resultado )




   



        

Fimalgoritmo