Algoritmo "raio de um círculo"
// Disciplina   : Lógica de Programação com o VISUALG
// Professor   : Jailson Costa Dos Santos 
// Descrição   : ele solicita a base e a altura e exibe o perímetro
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis
//entradas//
raio:real
altura:real
resultado:real

 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("digite o raio do circulo ")//saida
leia(raio)
resultado<- (2*3.14*raio)//procesamento
escreva("o valor do perimetro da circuferencia é: ", resultado) //saida



Fimalgoritmo