Algoritmo "Salário com Aumento"
// Disciplina   : Lógica de Programação com o VISUALG
// Professor   : Jailson Costa Dos Santos 
// Descrição   : salário atual de um funcionário e o percentual de aumento.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis
//entradas//
salario:real
percentual:real
resultado:real

 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("")



Fimalgoritmo