Algoritmo "Valor do seu antecessor"
// Disciplina   : Lógica de Programação com o VISUALG
// Professor   : Jailson Costa Dos Santos 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/03/2026
Var
// Seção de Declarações das variáveis
numero1:inteiro
resultado:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite um numero para descobrir o seu antecessor")
leia(numero1)
resultado <- (numero1 - 1)
escreva("O antecessor é: ", resultado)



Fimalgoritmo